config/routes.rb
Rails.application.routes.draw do

  root 'site#home'

  resources :users, only: [:index, :show, :edit, :update], param: :username do
    resources :projects
  end

  get "/users/:username/info", to: "users#info", as: "user_info"

  get  "/register", to: "registrations#new"
  post "/register", to: "registrations#create"

  post   "/login",  to: "login#create"
  delete "/logout", to: "login#destroy"

end

app/models/medium.rb
class Medium < ActiveRecord::Base
	belongs_to :project

	validates :mediatype, :link, :project_id, presence: true
	# validates :mediatype, inclusion: { in: %w(video, photo), message: "%{value} is not a valid media (at least yet!)" } 
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_attached_file :main_picture, styles: { medium: "300x300>", thumb: "100x100>" }
	
	validates :name, :user_id, presence: true
	validates_attachment_content_type :main_picture, :content_type => /\Aimage\/.*\Z/
	
	belongs_to :user
	has_many :media
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_attached_file :profile_picture, styles: { medium: "300x300>", thumb: "100x100>" }

	validates :username, :email, presence: true
	validates_attachment_content_type :profile_picture, :content_type => /\Aimage\/.*\Z/

	has_many :projects, dependent: :destroy

	def create_empty_project
		self.projects.create(
			name: "Portfolio"
			)
	end

	def to_param
  		username
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	include Pundit
	
	protect_from_forgery with: :exception

	helper_method :current_user_name

	def current_user_name
		current_user_name = session[:current_user_name]
		if current_user_name
		  @current_user ||= User.find_by username: current_user_name
		end
	end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

	def create
		user = User.where(email: params[:email]).first

		if !user
			flash[:warning] = "The email introduced is not registered"
		else
			if user.authenticate(params[:password])
				# Session engaged
				flash[:success] = "Login sucessful! Welcome #{user.username}!"

				session[:current_user_name] = user.username
			else
				flash[:error] = "Login was not sucessful, check the password provided"
			end
		end
		
		redirect_to root_path
	end

	def destroy
		temp_username = session[:current_user_name]

		session[:current_user_name] = nil

		flash[:notice] = "You correctly logged out. See you soon #{temp_username}!"

		respond_to do |format|
			format.html { redirect_to root_path }
			format.js   { render js: "window.location.href='#{root_path}'" }
		end
	end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

	def create
		user = User.where(email: params[:email]).first

		# Session engaged
		if user && user.authenticate(params[:password])
			flash[:success] = "Login sucessful! Welcome #{user.username}!"

			session[:current_user_id] = user.id
		else
			flash[:error] = "Login was not sucessful"
		end

		redirect_to root_path
	end

	def destroy
		session[:current_user_id] = nil

		respond_to do |format|
			format.html { redirect_to root_path }
			format.js   { render js: "window.location.href='#{root_path}'" }
		end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def show
		# TODO: Redirect to user's profile with the project filtered (2nd version)
		load_user()
		@project = @user.projects.find params[:id]
		@media = @project.media
	end

	def index
		load_user()
		@projects = @user.projects.includes(:media)
	end

	def new
		# TODO: When creating a new project, let the user select one of the media to be the project main_picture
		@project = Project.new
	end

	def create
		load_user()
		@project = @user.projects.new(project_params)
		if @project.save
			redirect_to user_path(@user.username)
		else
			render :new
		end
	end

	private

	def load_user
		@user = User.find_by username: params[:user_username]
	end

	def project_params
		params.require(:project).permit(:name, :company, :description)
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			# TODO: UserMailer.welcome(@user).deliver_now
			
			session[:current_user_name] = @user.username

			# We create the empty project: "Portfolio", for all separate photos
			# TODO: Validate the creation
			@user.create_empty_project
			redirect_to user_path(@user.username)
		else
			render :new
		end
		rescue ActiveRecord::RecordNotUnique
			@user.errors.add(:email, "There is already a user with this email")

			render :new
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :profile_picture, :password, :password_confirmation)
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

	before_action :load_best_projects, only: :home

	def home
	end

	def load_best_projects
		@projects = Project.all.order("total_likes DESC").includes(:user).includes(:media).limit(20)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :load_user, except: :index

	def index
		page  = params[:page].to_i || 1

		@users = User.order("username ASC").page(page)
	end

	def show
		@projects = @user.projects
	end

	def edit
	end

	def info
	end
	
	def update
		if @user.update_attributes(user_params)
			flash[:notice] = "User updated successfully"
			redirect_to user_path(@user.username)
		else
			flash[:error]  = "Ops! We couldn't update the user, please review the errors"
	
			render :edit
		end
	end

	private

	def load_user
    	@user = User.find_by username: params[:username]
  	end

  	def user_params
    	params.require(:user).permit(:username, :fullname, :styles, :summary, :born, :profile_picture, :nationality, :ethnicity, :languages, :height, :chest, :waist, :hips, :suit, :shirt, :pants, :shoes, :eyes, :hair, :actingexp, :battleexp, :adsexp, :teachingexp)
  	end

  	def deny_access
		render text: "Your are not authorized to perform this action", status: :unauthorized
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def give_thumbnail(link)
		video = VideoInfo.new(link)
		video.thumbnail_large.gsub("http", "https")
	end

	def youtube_sanitize(youtube_url)
		if youtube_url[/youtu\.be\/([^\?]*)/]
			youtube_id = $1
		else
			youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
			youtube_id = $5
		end

		%Q{https://www.youtube.com/embed/#{ youtube_id }}
	end

	def give_video_info(link)
		video = VideoInfo.new(link)
		video.title
	end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="container">
      <div class="navbar-header">
        <!-- Famous Burguer -->
        
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <!-- LOGO -->
        <a href="<%= root_path %>"> <%= image_tag("enliven-logo.png", alt: "ENLIVEN logo", class: "enliven-logo") %> </a>
        
      <!-- Search Field Small Screens-->
        <div class="col-xs-6 col-md-4 navbar-search-field-ss hidden-sm">
          <form class="navbar-form" role="search" method="get" id="search-form" name="search-form">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Users, projects and styles..." id="query" name="query" value="">
                  <div class="input-group-btn">
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                </div>
            </div>
          </form>
        </div>

      </div>
      <p class="navbar-text header-sentence"> The online portfolio for DANCERS </p>


      <!-- User interactions -->
      <div class="collapse navbar-collapse" id="bs-navbar-collapse-2">
        
      <!-- Search Field Large Screens-->
        <div class="col-xs-6 col-md-4 navbar-search-field-bs hidden-sm">
          <form class="navbar-form pull-right" role="search" method="get" id="search-form" name="search-form">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Users, projects and styles..." id="query" name="query" value="">
                  <div class="input-group-btn">
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                </div>
            </div>
          </form>
        </div>

        <% if current_user_name %>
          <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to current_user_name.username, user_path(current_user_name.username) %> </li>
            <li class="dropdown active">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li> <%= link_to "Edit Profile", edit_user_path(current_user_name.username) %> </li>
                <li><a href="#">Your Projects</a></li>
                <li class="divider"></li>
                <li> <%= link_to "Log out", logout_path, method: :delete, confirm: 'Logout?', remote: true %> </li>
              </ul>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li> <%= link_to "Register", register_path %> </li>
            <li> <a href="", id: "btn-login", data-toggle="modal", data-target="#login-modal"> Log In </a> </li>
          </ul>
        <% end %>
      </div>
    </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Enliven</title>
		<%= favicon_link_tag 'favicon.ico' %>
		<%= stylesheet_link_tag "application", '//fonts.googleapis.com/css?family=Pacifico', :media => "all" %>
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/navbar' %>

		<div class="flash-msg" id="flash-msg">
			<% flash.map do |key, msg| %>
				<% if key == "success" %>
					<%= content_tag :div, class: ["alert", "alert-success", "alert-dismissible"], role: "alert" do %>
						<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<p> <%= msg %> </p>
					<% end %>
				<% elsif key == "notice" %>
					<%= content_tag :div, class: ["alert", "alert-info", "alert-dismissible"], role: "alert" do %>
						<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<p> <%= msg %> </p>
					<% end %>
				<% elsif key == "warning" %>
					<%= content_tag :div, class: ["alert", "alert-warning", "alert-dismissible"], role: "alert" do %>
						<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<p> <%= msg %> </p>
					<% end %>
				<% elsif key == "error" %>
					<%= content_tag :div, class: ["alert", "alert-danger", "alert-dismissible"], role: "alert" do %>
						<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<p> <%= msg %> </p>
					<% end %>
				<% end %>					
			<% end %>
		</div>

		<%= yield %>

		<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="login-modal" aria-hidden="true">
			<div class="modal-dialog modal-sm">
				<div class="modal-content text-center">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h4 class="modal-title">Login to <%= image_tag("enliven-logo.png", alt: "ENLIVEN logo", class: "enliven-logo-login") %></h4>
					</div>
					<div class="modal-body">
						<div class="form-group">
							<%= bootstrap_form_tag url: login_path do %>
								<%= text_field_tag :email, nil, placeholder: "email", class: "form-control login-field" %>
								<%= password_field_tag :password, nil, placeholder: "password", class: "form-control login-field" %>
					</div>
					<div class="modal-footer">
						<%= submit_tag "Log in!", class: "btn btn-success" %>
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

app/views/projects/index.html.erb
<h1 class="text-center">Projects from <%= @user.username %> </h1>

<div class="col-sm-6 col-sm-offset-3">
	<div class="list-group">
	  <% @projects.each do |project| %>
	    <a href="<%= user_project_path(@user.username, project.id) %>" class="list-group-item">
			<p class="lead"> <%= project.name %> </p>
			<p> <%= project.company %> </p>
			<p> <strong> <%= project.total_likes %># </strong>enlivened </p>
	    </a>
	  <% end %>
	</div>
</div>

app/views/projects/new.html.erb
<h1 class="text-center"> Create a new Project here </h1>

<% if @project.errors.any? %>
  <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="col-sm-5 col-md-offset-3">
    <%= bootstrap_form_for @project, html: { multipart: true }, url: user_projects_path do |f| %>
      <%= f.text_field :name %>
      <%= f.text_field :company %>
      <%= f.text_area :description %>
      <%= f.submit "Create project", class: "btn btn-success" %>
      <%= link_to "Cancel", root_path, class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="jumbotron jumbo-cover">
	<div class="container">
		<h3> <strong> <%= @project.name %> </strong> <small> by <%= link_to @project.user.username, user_path(@project.user.username) %> </small> </h3>
		<h4> for: <strong> <%= @project.company %> </strong> </h4>
		<p> <%= @project.description %> </p>
		<h5> <%= @project.total_likes %># times enlivened </h5>
	</div>
</div>

<div class="row">
	<div class="col-xs-12 col-md-10 col-md-offset-1">
		<div class="media-container">
			<div class="medium-gutter"></div>
			<% @media.each do |medium| %>
				<div class="medium">
					<a href="", id: "media-modal", data-toggle="modal", data-target="#media-modal">
						<% if medium.mediatype == "photo" %>
							<%= image_tag(medium.link, alt: "Picture num. #{medium.id}", link: "#{medium.link}", typeofmedium: "#{medium.mediatype}") %>
						<% else %>
							<div class="play-button">
								<span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span>
							</div>
								<%= image_tag( give_thumbnail(medium.link), alt: give_video_info(medium.link), link: youtube_sanitize(medium.link), typeofmedium: "#{medium.mediatype}") %>
						<% end %>
					</a>
				</div>
			<% end %>
		</div>
	</div>
</div>

<div class="modal fade" id="media-modal" tabindex="-1" role="dialog" aria-labelledby="media-modal" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content text-center">
			<div class="modal-header" id="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> </br>
				<h4 class="modal-title"></h4>
			</div>
			<div class="modal-body" id="embedded_media">
				<!-- Media content (image/video) -->
			</div>
		</div>
	</div>
</div>

app/views/site/home.html.erb
<% unless current_user_name %>
	<div class="jumbotron initial-page">
		<div class="container text-center">
			<h2> Welcome to enliven! </h2>
		  	<h4 class="lead"> The online portfolio for <del>performing arts professionals</del> DANCERS!</h4>
		  	<p> <%= link_to "Make your portfolio now and start sharing!", register_path, class: "btn btn-success btn-lg", role: "button" %> </p>
		</div>
	</div>
<% else %>
	<div class="jumbotron initial-page-logged">
		<div class="container">
			<h2> Welcome back <%= link_to current_user_name.username, user_path(current_user_name) %>! </h2>
		  	<h4 class="lead"> You can directly access your profile features here: </h4>
			<div class="btn-group">
				<%= link_to "Check your profile", user_path(current_user_name), class: "btn btn-default" %>
				<%= link_to "Edit your profile", edit_user_path(current_user_name), class: "btn btn-default" %>
				<%= link_to "Check your projects", user_projects_path(current_user_name), class: "btn btn-default" %>
			</div>
		</div>
	</div>
<% end %>

<div class="container">
	<div class="row">
		<div class="best-projects-container">
			<div class="project-gutter"></div>
			<% @projects.each do |project| %>
				<div class="col-sm-6 col-md-3 one-project">
					<a href="<%= user_project_path(project.user.username,project.id)%>" >
						<div class="thumbnail">
							<% if project.media.count > 0 %>
								<%= image_tag(project.media.first.link, alt: "Project image", class: "home-projects-image") %>
							<% else %>
								<div class="text-center">
									<span class="glyphicon glyphicon-picture" aria-hidden="true" style="font-size: 70px;"></span>
									<p>Project with no media yet</p>
								</div>
							<% end %>
							<div class="caption">
								<h4> <%= link_to project.name, user_project_path(project.user.username, project.id) %> </h4>
								<p class="text-primary"> by <%= link_to project.user.username, user_path(project.user.username) %> </p>
								<p> <%= project.total_likes %># enlivened!</p>
							</div>
						</div>
					</a>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/site/home_old.html.erb
<% unless current_user_name %>
	<div class="jumbotron">
		<div class="container">
			<h2> Welcome to enliven! </h2>
		  	<h4 class="lead"> The online portfolio for <del>performing arts professionals</del> DANCERS!</h4>
		  	<p> <%= link_to "Make your portfolio now and start sharing!", register_path, class: "btn btn-success btn-lg", role: "button" %> </p>
		</div>
	</div>
<% else %>
	<div class="jumbotron">
		<div class="container">
			<h2> Welcome back <%= link_to current_user_name.username, user_path(current_user_name) %>! </h2>
		  	<h4 class="lead"> You can directly access your profile features here: </h4>
			<div class="btn-group btn-group-justified">
				<%= link_to "Check your profile", user_path(current_user_name), class: "btn btn-default" %>
				<%= link_to "Edit your profile", edit_user_path(current_user_name), class: "btn btn-default" %>
				<%= link_to "Check your projects", user_projects_path(current_user_name), class: "btn btn-default" %>
			</div>
		</div>
	</div>
<% end %>

<div class="container">
	<% @projects.each do |project| %>
	<div class="col-xs-6 col-md-3">
		<div class="thumbnail" style="backgound-color: blue;"></div>
		<div class="project-info">
			<p> 
				<h3> <%= link_to project.name, user_project_path(project.user.username, project.id) %> </h3>
				<p class="text-primary"> by <%= link_to project.user.username, user_path(project.user.username) %> </p>
				<p> <%= project.total_likes %># enlivened!</p>
			</p>
		</div>
	</div>
	<% end %>
</div>

app/views/users/_basics.html.erb
<%= bootstrap_form_for @user, html: { multipart: true } do |f| %>
  <%= f.text_field :email, readonly: true %>
  <%= f.text_field :fullname %>
  <%= f.date_field :born, label: "Birthday" %>
  <%= f.text_field :styles, placeholder: "ie. Housedance, Popping, Bboying, ..." %>
  <%= f.text_area :summary, placeholder: "Enter here a brief summary of your career as a dancer" %>
  <%= f.file_field :logo %>
  <%= f.submit "Save Changes", class: "btn btn-success" %>
  <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
<% end %>

app/views/users/_detailedbio.html.erb
<%= bootstrap_form_for @user, html: { multipart: true } do |f| %>
	<%= f.text_area :actingexp, label: "Acting experience", placeholder: "Enter here a brief summary of your acting experience" %>
	<%= f.text_area :battleexp, label: "Battling experience", placeholder: "Enter here a brief summary of your battling achievements" %>
	<%= f.text_area :adsexp, label: "Ads and Campaigns experience", placeholder: "Enter here a brief summary of your participation in Ads and Campaigns" %>
	<%= f.text_area :teachingexp, label: "Teaching experience", placeholder: "Enter here a brief summary of teaching experience" %>
	<%= f.submit "Save Changes", class: "btn btn-success" %>
	<%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
<% end %>

app/views/users/_measures.html.erb
<%= bootstrap_form_for @user, html: { multipart: true } do |f| %>
  <%= f.number_field :height %>
  <%= f.number_field :chest %>
  <%= f.number_field :waist %>
  <%= f.number_field :hips %>
  <%= f.text_field :suit, placeholder: "Your dress/suit size" %>
  <%= f.text_field :shirt, placeholder: "Your shirt size" %>
  <%= f.text_field :pants, placeholder: "Your pants size" %>
  <%= f.number_field :shoes, placeholder: "Your shoes number (USA size)" %>
  <%= f.text_field :eyes, placeholder: "Your eyes color" %>
  <%= f.text_field :hair, placeholder: "Your hair color, size, cut..." %>
  <%= f.submit "Save Changes", class: "btn btn-success" %>
  <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
<% end %>

app/views/users/_origins.html.erb
<%= bootstrap_form_for @user, html: { multipart: true } do |f| %>
  <%= f.date_field :born, label: "Birthday" %>
  <%= f.text_field :nationality, placeholder: "City, State" %>
  <%= f.text_field :ethnicity %>
  <%= f.text_field :languages, placeholder: "List all languages you can speak" %>
  <%= f.submit "Save Changes", class: "btn btn-success" %>
  <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
<% end %>

app/views/users/_security.html.erb
<%= bootstrap_form_for @user, html: { multipart: true } do |f| %>
  <%= f.password_field :password %>
  <%= f.password_field :password_confirmation, label: "Confirm password" %>
  <%= f.submit "Save Changes", class: "btn btn-success" %>
  <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
<% end %>

app/views/users/index.html.erb
<h1 class="text-center">All registered users</h1>

<div class="list-group text-center">
  <% @users.each do |user| %>
    <a href="<%= user_path(user.username) %>" class="list-group-item">
      <h4 class="list-group-item-heading"> @<%= user.username %> </h4>
      <h4 class="list-group-item-text"> <%= user.fullname %> </h4>
      <p class="list-group-item-text"> <strong> <%= user.styles %> </strong> </p>
    </a>
  <% end %>
</div>

<%= paginate @users %>

app/views/users/show.html.erb
<div class="jumbotron user-jumbo">
	<div class="container">
		<div class="col-sm-3">
			<a href="#" class="img-rounded">
					<% unless @user.profile_picture_file_name.nil? %>
						<%= image_tag @user.profile_picture.url(:medium), class: "img-rounded profile-pic" %>
					<% else %>
						<img src="/assets/default_profile_pic.png" alt="User profile picture" class="img-rounded profile-pic">
					<% end %>
			</a>
		</div>
		
		<div class="col-sm-7">
		<h1> <%= @user.fullname %> <%= link_to "(#{@user.username})", user_path(@user.username), class: "lead" %> </h1>
			<h2> <%= @user.nationality %> </h2>
			<p class="lead"> <%= @user.styles %> </p>
		</div>
		<div class="col-sm-7 col-sm-offset-3">
			<div class="btn-group">
				<%= link_to "All info", user_info_path(@user.username), class: "btn btn-primary" %>
				<%= link_to "All Projects", user_projects_path(@user.username), class: "btn btn-primary" %>
				<% if current_user_name && current_user_name.username == @user.username %>
					<%= link_to "Edit Profile", edit_user_path(current_user_name.username), class: "btn btn-success" %>
					<%= link_to "New Project", new_user_project_path(current_user_name.username), class: "btn btn-success" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

<!-- TODO: Convert all this code repetition into a partial -->
<div class="row">
	<div class="col-xs-12 col-md-10 col-md-offset-1">
		<div class="media-container">
			<div class="medium-gutter"></div>
			<% @projects.each do |project| %>
				<% project.media.each do |medium| %>
					<div class="medium">
						<a href="", id: "media-modal", data-toggle="modal", data-target="#media-modal">
							<% if medium.mediatype == "photo" %>
								<%= image_tag(medium.link, alt: "Picture num. #{medium.id}", link: "#{medium.link}", typeofmedium: "#{medium.mediatype}") %>
							<% else %>
								<div class="play-button">
									<span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span>
								</div>
									<%= image_tag( give_thumbnail(medium.link), alt: "Video num. #{medium.id}", link: youtube_sanitize(medium.link), typeofmedium: "#{medium.mediatype}") %>
							<% end %>
						</a>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

<div class="modal fade" id="media-modal" tabindex="-1" role="dialog" aria-labelledby="media-modal" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content text-center">
			<div class="modal-header" id="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button> </br>
				<h4 class="modal-title"></h4>
			</div>
			<div class="modal-body" id="embedded_media">
				<!-- Media content (image/video) -->
			</div>
		</div>
	</div>
</div>

app/views/users/show_old.html.erb
<!-- User's page header -->
<header class="col-sm-10">
	<div class="row">
		<div class="col-sm-3 col-sm-offset-1">
			<a href="#" class="img-rounded">
				<% unless @user.profile_picture_file_name.nil? %>
					<%= image_tag @user.profile_picture.url(:medium), class: "img-thumbnail" %>
				<% else %>
					<img src="/assets/default_profile_pic.png" alt="User profile picture" class="img-thumbnail">
				<% end %>
			</a>
		</div>
		<div class="col-sm-7">
			<h1> <%= @user.fullname %> <%= link_to "(#{@user.username})", user_path(@user.username), class: "lead" %> </h1>
			<h2> <%= @user.nationality %> </h2>
			<p class="lead"> <%= @user.styles %> </p>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-10 col-sm-offset-1 user-header-buttons">
			<div class="col-sm-offset-4">
				<%= link_to "All info", user_info_path(@user.username), class: "btn btn-primary" %>
				<%= link_to "All Projects", user_projects_path(@user.username), class: "btn btn-primary" %>
				<% if current_user_name && current_user_name.username == @user.username %>
					<%= link_to "Edit Profile", edit_user_path(current_user_name.username), class: "btn btn-info" %>
					<%= link_to "New Project", new_user_project_path(current_user_name.username), class: "btn btn-info" %>
				<% end %>
			</div>
		</div>
	</div>
</header>

<div class="row">
	<h3 class="text-center"> Here goes the selectors </h3>
</div>
<div class="row">
	<h3 class="text-center"> Here goes the images content </h3>
</div>